name: google_facbook_siging_package
description: Flutter plugin for Google Sign-In, a secure authentication system for signing in with a Google account on Android And The easiest way to add facebook login to your flutter app, get user information, profile picture and more.

version: 0.0.1
homepage: https://github.com/Gaurav123/google_facbook_siging_package
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"



dependencies:
  flutter:
    sdk: flutter
  google_sign_in_platform_interface: ^2.1.0
  google_sign_in_web: ^0.10.0
  meta: ^1.3.0
  flutter_facebook_auth_platform_interface: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
